package Inheritence;

class Parent9
{
	Parent9()
	{
		System.out.println("parent class 0-args constructor");
	}
}
public class Child9 extends Parent9{
	
	/* code is generated by compiler
	 Child9()
	 {
	   super();
	 }
	 */

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		new Child9();
	}

}
