package Inheritence;

class Parent8
{
	Parent8(int a)
	{
		//super();  generated by compiler, object class 0-args constructor will be executed
		System.out.println("1-args parent class constructor");
	}
}
public class Child8 extends Parent8{
	
	Child8()
	{
		//super();   generated by compiler, but in parent class there is no 0-args constructor so it's generate error message 
		System.out.println("0-args child class constructor");
	}
	
	Child8(int a)
	{
		//super();  generated by compiler, but in parent class there is no 0-args constructor so it's generate error message    
		System.out.println("1-args child class constructor");
	}

	public static void main(String[] args) {
		// TODO Auto-generated method stub
 
		new Child8();
		new Child8(10);
	}

}
