package Inheritence;

//Parent class constructor
class Parent7
{
	Parent7()
	{
		System.out.println("0-args parent class constructor");
	}
}
public class Child7 extends Parent7{
	
	Child7()
	{
		//super();    compiler generated code
		System.out.println("0-args child class constructor");
	}
	
	Child7(int a)
	{
		//super();     generated by compiler
		System.out.println("1-args child class constructor");
	}

	public static void main(String[] args) {
		// TODO Auto-generated method stub
 
		new Child7();
		new Child7(10);
	}

}
